"""add ai_analysis coloum to astro table

Revision ID: d7c978e6970d
Revises: e42658fd3f3f
Create Date: 2026-01-22 20:34:45.651559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c978e6970d'
down_revision: Union[str, Sequence[str], None] = 'e42658fd3f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('astro', sa.Column('ai_analysis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('astro', 'ai_analysis')
    # ### end Alembic commands ###
